version: '3.7'
services:
    etcd:
      hostname: etcd
      image: bitnami/etcd:3.5.14
      container_name: etcd
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      privileged: true
      volumes:
        - "./etcd:/bitnami/etcd/data"
      environment:
        - "ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379"
        - "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
        - "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
        - "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380"
        #参数指不用密码可以连接
        - "ALLOW_NONE_AUTHENTICATION=yes"
        - "ETCD_INITIAL_CLUSTER=node1=http://0.0.0.0:2380"
        - "ETCD_NAME=node1"
        - "ETCD_DATA_DIR=/opt/bitnami/etcd/data"
      ports:
        - 2379:2379
        - 2380:2380
 